-- Seed Data for CTU Clean-Track-Update
-- Run this after all migrations

-- Insert report reasons
INSERT INTO report_reasons (name, description) VALUES
    ('Trash left in room', 'Garbage, wrappers, or other waste materials left behind'),
    ('Dirty floor', 'Floor has visible dirt, stains, or spills'),
    ('Dirty chairs/desks', 'Chairs or desks have dust, stains, or writing on them'),
    ('Food waste', 'Food remnants, crumbs, or spilled drinks'),
    ('Unclean board', 'Whiteboard/blackboard has old markings or eraser dust'),
    ('Improperly arranged chairs', 'Chairs and desks not returned to proper arrangement'),
    ('Dust/dirt present', 'Visible dust on surfaces, windowsills, or equipment'),
    ('Damaged or messy classroom area', 'Broken furniture, vandalism, or general disarray'),
    ('Other', 'Any other cleanliness issue not listed above')
ON CONFLICT DO NOTHING;

-- Sample rooms (QR tokens will be generated by the application)
-- These are placeholder rooms - actual QR tokens should be generated via the admin interface
INSERT INTO rooms (room_code, room_name, building, floor, description, qr_token) VALUES
    ('LAB-101', 'Computer Laboratory 101', 'Main Building', '1', 'Computer laboratory with 50 workstations', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('LAB-102', 'Computer Laboratory 102', 'Main Building', '1', 'Computer laboratory with 50 workstations', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('ROOM-201', 'Lecture Room 201', 'Main Building', '2', 'Standard lecture room, capacity 60', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('ROOM-202', 'Lecture Room 202', 'Main Building', '2', 'Standard lecture room, capacity 60', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('LAB-301', 'Electronics Laboratory 301', 'Engineering Building', '3', 'Electronics lab with testing equipment', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('LAB-302', 'Electronics Laboratory 302', 'Engineering Building', '3', 'Electronics lab with testing equipment', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('ROOM-101', 'Classroom 101', 'Arts Building', '1', 'General classroom, capacity 45', 'qr_' || encode(gen_random_bytes(32), 'hex')),
    ('ROOM-102', 'Classroom 102', 'Arts Building', '1', 'General classroom, capacity 45', 'qr_' || encode(gen_random_bytes(32), 'hex'))
ON CONFLICT (room_code) DO NOTHING;

-- Note: Sections and admin users should be created through the admin interface
-- after the application is running, as they require Supabase Auth users to be created first.

-- Sample schedule template (will need actual section_ids and room_ids)
-- INSERT INTO schedules (section_id, room_id, subject_name, instructor_name, day_of_week, start_time, end_time)
-- VALUES 
--     ((SELECT id FROM sections WHERE section_name = 'A' AND program = 'BSIT' AND year_level = '4' LIMIT 1),
--      (SELECT id FROM rooms WHERE room_code = 'LAB-101'),
--      'Capstone Project', 'Dr. Juan Dela Cruz', 1, '08:00', '11:00');